library(shiny)
library(ggplot2)
library(dplyr)
library(maps)
library(plotly)
library(utils)
data <- read.table("https://raw.githubusercontent.com/info-201a-wi22/final-project-starter-KaidiKelsey/main/docs/WE0_data_cleaned.txt"
         ,header = TRUE, stringsAsFactors = FALSE)

server <- function(input, output,session) {
  output$chart3 <- renderPlotly({
    year_range <- seq(input$year_input[1],input$year_input[2])
    year_range <- paste("X", year_range, sep = "")
    map_data <- data %>% 
      filter(Subject.Descriptor == input$subject_input)%>%   
      group_by(Country)%>%      #Group the data by country
      select(Country, year_range)%>%  #Keep only the numeric data from year of 2000 to 2021
      rowwise()
    map_data$Average <- rowMeans(map_data[,-1],na.rm = FALSE)
    world <- map_data("world")
    names(world)[names(world) == "region"] <- "Country"
    world$Country[which(world$Country == "USA")] = "United States"
    world <- left_join(world, map_data, by = "Country")
    map <- ggplot(world, aes(x = long, y = lat, group = group)) + 
      geom_polygon(aes(fill =Average),color = NA) +
      scale_fill_continuous(name = "Average") + 
      labs(title = paste("Average",input$subject_input, "around the world"))
    ggplotly(map)
  })
  output$intro <- renderUI({
    text_1 <- "Our study project will be focused on the issue of globalized Gross Domestic Product, 
    which is a key indication of national economic data and a common gauge of a region’s economic 
    status and overall degree of development. In general, the GDP of a country may be split into 
    three categories: value, income, and product. It is the difference in value between the total 
    value of all products and services generated by all resident units in a given period and the 
    total value of all non-fixed assets, goods, and services invested in the same period. More 
    specifically, we will investigate the influence and link between population, inflation, and 
    unemployment on GDP. Meanwhile, using data from 2000 to 2021, we will analysis the economic 
    environment across all region and for forecast for the future."
    HTML(text_1)
  }) 
}

